# Generated by Django 3.0.5 on 2020-08-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registered',
            field=models.DateField(),
        ),
    ]
